In [1]:
import pandas as pd

## Data Loading (Original Data)

In [2]:
pd.set_option('display.max_columns' , 44)

In [3]:
df = pd.read_csv('311_Service_Requests_Sample.csv')
df

C:\Users\clt\AppData\Local\Temp\ipykernel_23104\1469666211.py:1: DtypeWarning: Columns (0: Incident Zip, 1: Due Date, 2: Vehicle Type) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('311_Service_Requests_Sample.csv')

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Additional Details,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Intersection Street 1,Intersection Street 2,Address Type,City,Landmark,Facility Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board,Council District,Police Precinct,BBL,Borough,X Coordinate (State Plane),Y Coordinate (State Plane),Open Data Channel Type,Park Facility Name,Park Borough,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,57781330,06/01/2023 01:04:22 AM,06/07/2023 11:53:03 AM,HPD,Department of Housing Preservation and Develop...,PLUMBING,BASIN/SINK,BASIN BROKEN/LEAKING,RESIDENTIAL BUILDING,10035.0,417 EAST 118 STREET,EAST 118 STREET,NaN,NaN,NaN,NaN,ADDRESS,NEW YORK,NaN,NaN,Closed,NaN,The Department of Housing Preservation and Dev...,06/07/2023 12:00:00 AM,11 MANHATTAN,8.0,Precinct 25,1.018060e+09,MANHATTAN,"1,002,564","229,676",PHONE,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.797065,-73.933855,POINT (-73.933855127566 40.797064609741)
1,57765916,06/01/2023 01:04:11 AM,06/01/2023 01:36:43 AM,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,NaN,Street/Sidewalk,10468.0,2196 CEDAR AVENUE,CEDAR AVENUE,WEST 179 STREET,WEST 182 STREET,WEST 179 STREET,WEST 182 STREET,ADDRESS,BRONX,CEDAR AVENUE,NaN,Closed,NaN,The Police Department reviewed your complaint ...,06/01/2023 01:36:48 AM,07 BRONX,14.0,Precinct 52,2.032320e+09,BRONX,"1,008,221","252,817",MOBILE,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.860566,-73.913341,POINT (-73.913341007678 40.860566468128)
2,57765849,06/01/2023 01:03:51 AM,06/01/2023 01:35:53 AM,NYPD,New York City Police Department,Illegal Parking,Blocked Sidewalk,NaN,Street/Sidewalk,11230.0,1000 OCEAN PARKWAY,OCEAN PARKWAY,BAY PARKWAY,AVENUE J,BAY PARKWAY,AVENUE J,ADDRESS,BROOKLYN,OCEAN PARKWAY,NaN,Closed,NaN,The Police Department responded and upon arriv...,06/01/2023 01:35:58 AM,12 BROOKLYN,44.0,Precinct 66,3.065180e+09,BROOKLYN,"992,433","166,759",PHONE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.624388,-73.970522,POINT (-73.970521835652 40.624387651877)
3,57763199,06/01/2023 01:03:49 AM,06/01/2023 01:10:17 AM,NYPD,New York City Police Department,Illegal Parking,Double Parked Blocking Traffic,NaN,Street/Sidewalk,11203.0,744 LEFFERTS AVENUE,LEFFERTS AVENUE,TROY AVENUE,SCHENECTADY AVENUE,TROY AVENUE,SCHENECTADY AVENUE,ADDRESS,BROOKLYN,LEFFERTS AVENUE,NaN,Closed,NaN,The Police Department responded and upon arriv...,06/01/2023 01:10:22 AM,09 BROOKLYN,41.0,Precinct 71,3.014290e+09,BROOKLYN,"1,001,948","180,923",MOBILE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.663251,-73.936208,POINT (-73.936208170434 40.663250874263)
4,57767852,06/01/2023 01:03:31 AM,06/01/2023 01:12:32 AM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,Residential Building/House,10009.0,116 AVENUE C,AVENUE C,EAST 7 STREET,EAST 8 STREET,EAST 7 STREET,EAST 8 STREET,ADDRESS,NEW YORK,AVENUE C,NaN,Closed,NaN,The Police Department responded to the complai...,06/01/2023 01:12:37 AM,03 MANHATTAN,2.0,Precinct 9,1.003770e+09,MANHATTAN,"990,179","203,199",ONLINE,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.724409,-73.978610,POINT (-73.978609514106 40.724409035027)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3129047,54336471,06/01/2022 01:08:15 AM,06/01/2022 01:40:44 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,NaN,Street/Sidewalk,10024.0,117 WEST 90 STREET,WEST 90 STREET,COLUMBUS AVENUE,AMSTERDAM AVENUE,COLUMBUS AVENUE,AMSTERDAM AVENUE,ADDRESS,NEW YORK,WEST 90 STREET,NaN,Closed,NaN,The Police Department responded to the complai...,06/01/2022 01:40:47 AM,07 MANHATTAN,6.0,Precinct 24,1.012210e+09,MANHATTAN,"992,231","226,888",MOBILE,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.789428,-73.971178,POINT (-73.97117824441 40.789427677463)
3129048,54331567,06/01/2022 01:07:59 AM,06/01/2022 03:43:09 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Talking,NaN,Store/Commercial,10466.0,4340 WHITE PLAINS ROAD,WHITE PLAINS ROAD,EAST 236 STREET,EAST 237 STREET,EAST 236 STREET,EAST 237 STREET,ADDRESS,BRONX,WHITE PLAINS ROAD,NaN,Closed,NaN,The Police Department responded to the complai...,06/01/2022 03:43:13 AM,12 BRONX,11.0,Precinct 47,2.050430e+09,BRONX,"1,024,188","266,003",MOBILE,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.896700,-73.855539,POINT (-73.855539223035 40.896700107848)
3129049,54338347,06/01/2022 01:06:46 AM,06/02/2022 11:00:32 AM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,Residential Building/House,10466.0,672 EAST 231 STREET,EAST 231 STREET,CARPENTER AVENUE,WHITE PLAINS ROAD LINE,CARPENTER AVENUE,WHITE PLAINS ROAD LINE,ADDRESS,BRONX,EAST 231 STREET,NaN,Closed,NaN,The Police Department responded to the complai...,06/02/2022 11:01:13 AM,12 BRONX,12.0,Precinct 47,2.048330e+09,BRONX,"1,023,174","264,429",MOBILE,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.892385,-73.859216,POINT (-73.859216132567 40.892384515391)
3129050,54336483,06/01/2022 01:06:42 AM,06/01/2022 01:20:07 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,NaN,Street/Sidewalk,11236.0,653 EAST 108 STREET,EAST 108 STREET,FARRAGUT ROAD,GLENWOOD ROAD,FARRAGUT ROAD,GLENWOOD ROAD,ADDRESS,BROOKLYN,EAST 108 STREET,NaN,Closed,NaN,The Police Department responded to the complai...,06/01/2022 01:20:14 AM,18 BROOKLYN,42.0,Precinct 69,3.081580e+09,BROOKLYN,"1,013,409","176,488",ONLINE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.651047,-73.894917,POINT (-73.894916600624 40.651047454164)
3129051,54330314,06/01/2022 01:05:52 AM,06/01/2022 03:58:25 AM,NYPD,New York City Police Department,Noise - Residential,Loud Talking,NaN,Residential Building/House,10452.0,1065 JEROME AVENUE,JEROME AVENUE,WEST 165 STREET,WEST 166 STREET,WEST 165 STREET,WEST 166 STREET,ADDRESS,BRONX,JEROME AVENUE,NaN,Closed,NaN,The Police Department responded to the complai...,06/01/2022 03:58:33 AM,04 BRONX,8.0,Precinct 44,2.025050e+09,BRONX,"1,005,030","242,963",MOBILE,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.833528,-73.924908,POINT (-73.924907514463 40.833528237857)

### Load useful Columns

In [4]:
cols_to_save = [
    'Created Date', 'Closed Date', 'Agency Name',
       'Problem (formerly Complaint Type)',
       'Problem Detail (formerly Descriptor)', 'Incident Zip',
       'Status', 'Due Date','Resolution Action Updated Date',
       'Police Precinct','Borough','Open Data Channel Type',
       'Latitude', 'Longitude','Street Name','Resolution Description'	
]

df = pd.read_csv('311_Service_Requests_Sample.csv' , usecols=cols_to_save , low_memory= False)
df

,Created Date,Closed Date,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Incident Zip,Street Name,Status,Due Date,Resolution Description,Resolution Action Updated Date,Police Precinct,Borough,Open Data Channel Type,Latitude,Longitude
0,06/01/2023 01:04:22 AM,06/07/2023 11:53:03 AM,Department of Housing Preservation and Develop...,PLUMBING,BASIN/SINK,10035,EAST 118 STREET,Closed,NaN,The Department of Housing Preservation and Dev...,06/07/2023 12:00:00 AM,Precinct 25,MANHATTAN,PHONE,40.797065,-73.933855
1,06/01/2023 01:04:11 AM,06/01/2023 01:36:43 AM,New York City Police Department,Illegal Parking,Blocked Hydrant,10468,CEDAR AVENUE,Closed,NaN,The Police Department reviewed your complaint ...,06/01/2023 01:36:48 AM,Precinct 52,BRONX,MOBILE,40.860566,-73.913341
2,06/01/2023 01:03:51 AM,06/01/2023 01:35:53 AM,New York City Police Department,Illegal Parking,Blocked Sidewalk,11230,OCEAN PARKWAY,Closed,NaN,The Police Department responded and upon arriv...,06/01/2023 01:35:58 AM,Precinct 66,BROOKLYN,PHONE,40.624388,-73.970522
3,06/01/2023 01:03:49 AM,06/01/2023 01:10:17 AM,New York City Police Department,Illegal Parking,Double Parked Blocking Traffic,11203,LEFFERTS AVENUE,Closed,NaN,The Police Department responded and upon arriv...,06/01/2023 01:10:22 AM,Precinct 71,BROOKLYN,MOBILE,40.663251,-73.936208
4,06/01/2023 01:03:31 AM,06/01/2023 01:12:32 AM,New York City Police Department,Noise - Residential,Loud Music/Party,10009,AVENUE C,Closed,NaN,The Police Department responded to the complai...,06/01/2023 01:12:37 AM,Precinct 9,MANHATTAN,ONLINE,40.724409,-73.978610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3129047,06/01/2022 01:08:15 AM,06/01/2022 01:40:44 AM,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,10024,WEST 90 STREET,Closed,NaN,The Police Department responded to the complai...,06/01/2022 01:40:47 AM,Precinct 24,MANHATTAN,MOBILE,40.789428,-73.971178
3129048,06/01/2022 01:07:59 AM,06/01/2022 03:43:09 AM,New York City Police Department,Noise - Commercial,Loud Talking,10466,WHITE PLAINS ROAD,Closed,NaN,The Police Department responded to the complai...,06/01/2022 03:43:13 AM,Precinct 47,BRONX,MOBILE,40.896700,-73.855539
3129049,06/01/2022 01:06:46 AM,06/02/2022 11:00:32 AM,New York City Police Department,Noise - Residential,Loud Music/Party,10466,EAST 231 STREET,Closed,NaN,The Police Department responded to the complai...,06/02/2022 11:01:13 AM,Precinct 47,BRONX,MOBILE,40.892385,-73.859216
3129050,06/01/2022 01:06:42 AM,06/01/2022 01:20:07 AM,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,11236,EAST 108 STREET,Closed,NaN,The Police Department responded to the complai...,06/01/2022 01:20:14 AM,Precinct 69,BROOKLYN,ONLINE,40.651047,-73.894917
3129051,06/01/2022 01:05:52 AM,06/01/2022 03:58:25 AM,New York City Police Department,Noise - Residential,Loud Talking,10452,JEROME AVENUE,Closed,NaN,The Police Department responded to the complai...,06/01/2022 03:58:33 AM,Precinct 44,BRONX,MOBILE,40.833528,-73.924908

### Rename Columns

In [5]:
'Open Data Channel Type'.lower().replace(' ','_')

'open_data_channel_type'

In [6]:
def rename_cols(x):
    return x.lower().replace(' ','_')

df.columns = df.columns.map(rename_cols)
df.columns

Index(['created_date', 'closed_date', 'agency_name',
       'problem_(formerly_complaint_type)',
       'problem_detail_(formerly_descriptor)', 'incident_zip', 'street_name',
       'status', 'due_date', 'resolution_description',
       'resolution_action_updated_date', 'police_precinct', 'borough',
       'open_data_channel_type', 'latitude', 'longitude'],
      dtype='str')

In [7]:
df.rename(columns ={'problem_(formerly_complaint_type)' :'complaint_type',
                        'problem_detail_(formerly_descriptor)' : 'complaint_detail'} , inplace=True)

In [8]:
df.columns

Index(['created_date', 'closed_date', 'agency_name', 'complaint_type',
       'complaint_detail', 'incident_zip', 'street_name', 'status', 'due_date',
       'resolution_description', 'resolution_action_updated_date',
       'police_precinct', 'borough', 'open_data_channel_type', 'latitude',
       'longitude'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3129052 entries, 0 to 3129051
Data columns (total 16 columns):
 #   Column                          Dtype
---  ------                          -----
 0   created_date                    str
 1   closed_date                     str
 2   agency_name                     str
 3   complaint_type                  str
 4   complaint_detail                str
 5   incident_zip                    str
 6   street_name                     str
 7   status                          str
 8   due_date                        str
 9   resolution_description          str
 10  resolution_action_updated_date  str
 11  police_precinct                 str
 12  borough                         str
 13  open_data_channel_type          str
 14  latitude                        float64
 15  longitude                       float64
dtypes: float64(2), str(14)
memory usage: 1.4 GB

### Parsing Date from str to DateTime

In [12]:
date_cols =['created_date' , 'closed_date' ,'due_date','resolution_action_updated_date']

df[date_cols] = df[date_cols].apply(pd.to_datetime, format='%m/%d/%Y %I:%M:%S %p', errors='coerce')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3129052 entries, 0 to 3129051
Data columns (total 16 columns):
 #   Column                          Dtype
---  ------                          -----
 0   created_date                    datetime64[us]
 1   closed_date                     datetime64[us]
 2   agency_name                     str
 3   complaint_type                  str
 4   complaint_detail                str
 5   incident_zip                    str
 6   street_name                     str
 7   status                          str
 8   due_date                        datetime64[us]
 9   resolution_description          str
 10  resolution_action_updated_date  datetime64[us]
 11  police_precinct                 str
 12  borough                         str
 13  open_data_channel_type          str
 14  latitude                        float64
 15  longitude                       float64
dtypes: datetime64[us](4), float64(2), str(10)
memory usage: 1.2 GB

In [ ]:
df.duplicated().sum()

np.int64(19892)

### Check Missing Values

In [ ]:
df.isna().mean() * 100

created_date                       0.000000
closed_date                        0.901935
agency_name                        0.000000
complaint_type                     0.000000
complaint_detail                   2.961216
incident_zip                       1.267636
street_name                        4.640862
status                             0.000000
due_date                          99.758393
resolution_description             0.718684
resolution_action_updated_date     0.361132
police_precinct                    0.000000
borough                            0.000000
open_data_channel_type             0.000000
latitude                           1.581374
longitude                          1.581374
dtype: float64

## NANs Handling Approach

- Keeping the NANs in [closed_date, resolution_action_updated_date] is meaningful —
  NaT indicates the complaint is still open or has no action taken yet.
- Replacing the NANs in [complaint_detail] with 'No Detail'.
- Replacing the NANs in [resolution_description] with 'No Resolution Yet'.
- Dropping the NANs in [street_name] and [incident_zip] as they represent
  a very small percentage of the data and borough already covers location.
- Dropping the NANs in both [latitude] and [longitude] 
- Dropping [due_date] column entirely as 99.7% of its values are missing.

In [14]:
df['complaint_detail'] = df['complaint_detail'].fillna('No Detail')

In [17]:
df['resolution_description'] = df['resolution_description'].fillna('No Resolution Yet')

In [18]:
df.dropna(subset=['street_name' , 'incident_zip'] , inplace=True)

In [ ]:
df.dropna(subset=['latitude' , 'longitude'] , inplace=True)

In [20]:
df.drop(columns=['due_date'] , inplace=True)

In [21]:
df.duplicated().sum()

np.int64(18330)

In [22]:
before = len(df)
df.drop_duplicates(inplace=True)
after = len(df)

print(f"Dropped duplicates: {before - after}")
print(f"Remaining rows: {after}")

Dropped duplicates: 18330
Remaining rows: 2930915

In [27]:
df.to_parquet('nyc_cleaned.parquet', compression='snappy')